### ISSUE TITLE
Sort queries by time

### ISSUE THREAD

**Issue by Mariyo** [Zemistr/notorm-tracy-panel#1]
Hello,

I propose to insert this code to sort queries by execution time:
```php
        if ($this->queries) {

            usort($this->queries, function ($a, $b) {
                return $b[2] <=> $a[2];
            });

            foreach ($this->queries as list($sql, $params, $time)) {
```

https://github.com/Zemistr/notorm-tracy-panel/blob/e93a451081c564521460a54f7a57b37c8ef80ce7/NotOrmTracyPanel.php#L142-L143

**Comment by Zemistr** [comment]
Hi @Mariyo :)
Sorry for late answer.
I think I understand why you want this piece of code...but this is just a log of queries.
Maybe you can do it as a feature in JS and use it in the template. :)
